---
- id: terraform-fmt
  name: terraform-fmt
  description: Format terraform files
  entry: hooks/terraform-fmt
  language: script
  files: (\.tf|\.tfvars)$

- id: shfmt
  name: Check shell script style with shfmt
  language: script
  entry: hooks/shfmt
  types: [shell]

- id: shfmt-docker
  name: Check shell script style with shfmt trough a docker container
  language: docker_image
  types: [shell]
  args: ["-w"]
  entry: docker.io/mvdan/shfmt

- id: shellcheck
  name: Check shell scripts with shellcheck
  entry: hooks/shellcheck
  language: script
  types: [shell]
  args: [-e, SC1091]
