---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: requirements-txt-fixer
    - id: no-commit-to-branch

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck (local)
        language: script
        entry: hooks/shellcheck
        types: [shell]

      - id: shfmt
        name: shfmt (local)
        language: script
        entry: hooks/shfmt
        types: [shell]
