#!/usr/bin/env bash

set -e -o pipefail

# shellcheck disable=SC2155 # No way to assign to readonly variable in separate lines
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=hooks/_common.sh
source "$SCRIPT_DIR/_common.sh"

common::check-command shfmt

readonly cmd="shfmt -w $*"
${cmd}
