#!/usr/bin/env bash

filearray=("$@")

function format {
	terraform fmt "$1"
	return $?
}

exit_code=0
for file in "${filearray[@]}"; do
	format "$file"
	if [ $? -ne 0 ]; then
		exit_code=$?
	fi
done

exit $exit_code
