#!/usr/bin/env bash

set -e -o pipefail

if ! command -v terraform &> /dev/null ; then
    echo "terraform not installed or available in the PATH" >&2
    exit 1
fi

filearray=("$@")

exit_code=0
for file in "${filearray[@]}"; do
	terraform fmt "$1"

	if [ $? -ne 0 ]; then
		exit_code=$?
	fi
done

exit $exit_code
